---
- hosts: centos_nginx1 
  become: true
 
  tasks:
    - name: 'Add epel-release repo'
      yum:
        name: 'epel-release'
        state: present
    - name: 'Install nginx'
      yum:
        name: 'nginx'
        state: present
    - name: 'Insert Index Page'
      template:
        src: 'index.html.j2'
        dest: '/usr/share/nginx/html/index.html'
    - name: 'Setup nginx conf'
      template:
        src: 'nginx.conf.j2'
        dest: '/etc/nginx/nginx.conf'
      notify: 'restart nginx'
    - name: 'Start NGiNX'
      service:
        name: 'nginx'
        state: started
 
  handlers:
    - name: 'restart nginx'
      service:
        name: 'nginx'
        state: restarted
